name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Connect to AKS
      run: az aks get-credentials -g maharaja -n maharajaaks

    - name: Update HTML ConfigMap & restart pods
      run: |
        kubectl create configmap aks-html-page --from-file=index.html -o yaml --dry-run=client | kubectl apply -f -
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl rollout restart deployment aks-html-app

