name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Connect to AKS
      run: az aks get-credentials -g maharaja -n maharajaaks

    - name: Update HTML ConfigMap & restart pods
      run: |
        # 1️⃣ Create or update ConfigMap from index.html
        kubectl create configmap aks-html-page --from-file=index.html --dry-run=client -o yaml | kubectl apply -f -
        
        # 2️⃣ Apply deployment and service (ensures YAML changes are applied)
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml

        # 3️⃣ Restart deployment so pods pick up new HTML
        kubectl rollout restart deployment aks-html-app

